apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-certsecrets
  labels:
    {{- include "connector.labels" . | nindent 4 }}
data:
  cert.pfx: {{ .Values.service.certs.certPfx | toYaml | indent 2 }}
  cert.pem: {{ .Values.service.certs.certPem | toYaml | indent 2 }}
  key.pem: {{ .Values.service.certs.keyPem | toYaml | indent 2 }}