apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "connector.fullname" . }}-gaiaxpvc
  labels:
    {{- include "connector.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi